openapi: 3.0.0
info:
  title: Open Service Broker API
  description: The Open Service Broker API defines an HTTP(S) interface between Platforms
    and Service Brokers.
  contact:
    name: Open Service Broker API
    url: https://www.openservicebrokerapi.org/
    email: open-service-broker-api@googlegroups.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: master - might contain changes that are not yet released
externalDocs:
  description: The offical Open Service Broker API specification
  url: https://github.com/openservicebrokerapi/servicebroker/
servers:
- url: http://example.com
  description: Broker Endpoint
- url: http://localhost:3000
  description: OSB Checker - MockOSB
security:
- basicAuth: []
tags:
- name: Open Service Broker API Specification
paths:
  /v2/catalog:
    get:
      tags:
      - Catalog
      summary: get the catalog of services that the service broker offers
      operationId: catalog.get
      parameters:
      - name: X-Broker-API-Version
        in: header
        description: version number of the Service Broker API that the Platform will
          use
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: "2.13"
      responses:
        "200":
          description: catalog response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Catalog'
  /v2/service_instances/{instance_id}:
    get:
      tags:
      - ServiceInstances
      summary: get a service instance
      operationId: serviceInstance.get
      parameters:
      - name: X-Broker-API-Version
        in: header
        description: version number of the Service Broker API that the Platform will
          use
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: "2.13"
      - name: X-Broker-API-Originating-Identity
        in: header
        description: identity of the user that initiated the request from the Platform
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: instance_id
        in: path
        description: instance id of instance to fetch
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: service_id
        in: query
        description: id of the service associated with the instance
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: plan_id
        in: query
        description: id of the plan associated with the instance
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInstanceResource'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
      - ServiceInstances
      summary: provision a service instance
      operationId: serviceInstance.provision
      parameters:
      - name: X-Broker-API-Version
        in: header
        description: version number of the Service Broker API that the Platform will
          use
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: "2.13"
      - name: X-Broker-API-Originating-Identity
        in: header
        description: identity of the user that initiated the request from the Platform
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: instance_id
        in: path
        description: instance id of instance to provision
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: accepts_incomplete
        in: query
        description: asynchronous operations supported
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      requestBody:
        description: parameters for the requested service instance provision
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceInstanceProvisionRequestBody'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInstanceProvisionResponse'
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInstanceProvisionResponse'
        "202":
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInstanceAsyncOperation'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
      - ServiceInstances
      summary: deprovision a service instance
      operationId: serviceInstance.deprovision
      parameters:
      - name: X-Broker-API-Version
        in: header
        description: version number of the Service Broker API that the Platform will
          use
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: "2.13"
      - name: X-Broker-API-Originating-Identity
        in: header
        description: identity of the user that initiated the request from the Platform
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: instance_id
        in: path
        description: id of instance being deleted
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: service_id
        in: query
        description: id of the service associated with the instance being deleted
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: plan_id
        in: query
        description: id of the plan associated with the instance being deleted
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: accepts_incomplete
        in: query
        description: asynchronous deprovision supported
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Object'
        "202":
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperation'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "410":
          description: Gone
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      tags:
      - ServiceInstances
      summary: update a service instance
      operationId: serviceInstance.update
      parameters:
      - name: X-Broker-API-Version
        in: header
        description: version number of the Service Broker API that the Platform will
          use
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: "2.13"
      - name: X-Broker-API-Originating-Identity
        in: header
        description: identity of the user that initiated the request from the Platform
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: instance_id
        in: path
        description: instance id of instance to update
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: accepts_incomplete
        in: query
        description: asynchronous operations supported
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      requestBody:
        description: parameters for the requested service instance update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceInstanceUpdateRequestBody'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Object'
        "202":
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInstanceAsyncOperation'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: Unprocessable entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v2/service_instances/{instance_id}/last_operation:
    get:
      tags:
      - ServiceInstances
      summary: get the last requested operation state for service instance
      operationId: serviceInstance.lastOperation.get
      parameters:
      - name: X-Broker-API-Version
        in: header
        description: version number of the Service Broker API that the Platform will
          use
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: "2.13"
      - name: instance_id
        in: path
        description: instance id of instance to find last operation applied to it
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: service_id
        in: query
        description: id of the service associated with the instance
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: plan_id
        in: query
        description: id of the plan associated with the instance
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: operation
        in: query
        description: a provided identifier for the operation
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          headers:
            Retry-After:
              description: Indicates when to retry the request
              required: false
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LastOperationResource'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "410":
          description: Gone
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v2/service_instances/{instance_id}/service_bindings/{binding_id}/last_operation:
    get:
      tags:
      - ServiceBindings
      summary: get the last requested operation state for service binding
      operationId: serviceBinding.lastOperation.get
      parameters:
      - name: X-Broker-API-Version
        in: header
        description: version number of the Service Broker API that the Platform will
          use
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: "2.13"
      - name: instance_id
        in: path
        description: instance id of instance to find last operation applied to it
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: binding_id
        in: path
        description: binding id of service binding to find last operation applied
          to it
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: service_id
        in: query
        description: id of the service associated with the instance
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: plan_id
        in: query
        description: id of the plan associated with the instance
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: operation
        in: query
        description: a provided identifier for the operation
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          headers:
            Retry-After:
              description: Indicates when to retry the request
              required: false
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LastOperationResource'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "410":
          description: Gone
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v2/service_instances/{instance_id}/service_bindings/{binding_id}:
    get:
      tags:
      - ServiceBindings
      summary: get a service binding
      operationId: serviceBinding.get
      parameters:
      - name: X-Broker-API-Version
        in: header
        description: version number of the Service Broker API that the Platform will
          use
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: "2.13"
      - name: X-Broker-API-Originating-Identity
        in: header
        description: identity of the user that initiated the request from the Platform
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: instance_id
        in: path
        description: instance id of instance associated with the binding
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: binding_id
        in: path
        description: binding id of binding to fetch
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: service_id
        in: query
        description: id of the service associated with the instance
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: plan_id
        in: query
        description: id of the plan associated with the instance
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceBindingResource'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
      - ServiceBindings
      summary: generate a service binding
      operationId: serviceBinding.binding
      parameters:
      - name: X-Broker-API-Version
        in: header
        description: version number of the Service Broker API that the Platform will
          use
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: "2.13"
      - name: X-Broker-API-Originating-Identity
        in: header
        description: identity of the user that initiated the request from the Platform
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: instance_id
        in: path
        description: instance id of instance to create a binding on
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: binding_id
        in: path
        description: binding id of binding to create
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: accepts_incomplete
        in: query
        description: asynchronous operations supported
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      requestBody:
        description: parameters for the requested service binding
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceBindingRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceBindingResponse'
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceBindingResponse'
        "202":
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperation'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
      - ServiceBindings
      summary: deprovision a service binding
      operationId: serviceBinding.unbinding
      parameters:
      - name: X-Broker-API-Version
        in: header
        description: version number of the Service Broker API that the Platform will
          use
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: "2.13"
      - name: X-Broker-API-Originating-Identity
        in: header
        description: identity of the user that initiated the request from the Platform
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: instance_id
        in: path
        description: id of the instance associated with the binding being deleted
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: binding_id
        in: path
        description: id of the binding being deleted
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: service_id
        in: query
        description: id of the service associated with the instance for which a binding
          is being deleted
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: plan_id
        in: query
        description: id of the plan associated with the instance for which a binding
          is being deleted
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: accepts_incomplete
        in: query
        description: asynchronous operations supported
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Object'
        "202":
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperation'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "410":
          description: Gone
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Catalog:
      type: object
      properties:
        services:
          type: array
          items:
            $ref: '#/components/schemas/Service'
      example:
        services:
        - bindable: true
          metadata: {}
          plan_updateable: true
          plans:
          - metadata: null
            bindable: true
            maintenance_info:
              description: description
              version: version
            schemas:
              service_binding:
                create: null
              service_instance:
                create:
                  parameters: {}
                update: null
            name: name
            description: description
            id: id
            free: true
          - metadata: null
            bindable: true
            maintenance_info:
              description: description
              version: version
            schemas:
              service_binding:
                create: null
              service_instance:
                create:
                  parameters: {}
                update: null
            name: name
            description: description
            id: id
            free: true
          name: name
          binding_rotatable: true
          description: description
          id: id
          dashboard_client:
            id: id
            secret: secret
            redirect_uri: redirect_uri
          tags:
          - tags
          - tags
          requires:
          - syslog_drain
          - syslog_drain
        - bindable: true
          metadata: {}
          plan_updateable: true
          plans:
          - metadata: null
            bindable: true
            maintenance_info:
              description: description
              version: version
            schemas:
              service_binding:
                create: null
              service_instance:
                create:
                  parameters: {}
                update: null
            name: name
            description: description
            id: id
            free: true
          - metadata: null
            bindable: true
            maintenance_info:
              description: description
              version: version
            schemas:
              service_binding:
                create: null
              service_instance:
                create:
                  parameters: {}
                update: null
            name: name
            description: description
            id: id
            free: true
          name: name
          binding_rotatable: true
          description: description
          id: id
          dashboard_client:
            id: id
            secret: secret
            redirect_uri: redirect_uri
          tags:
          - tags
          - tags
          requires:
          - syslog_drain
          - syslog_drain
    Service:
      required:
      - bindable
      - description
      - id
      - name
      - plans
      type: object
      properties:
        name:
          type: string
        id:
          type: string
        description:
          type: string
        tags:
          type: array
          items:
            type: string
        requires:
          type: array
          items:
            type: string
            enum:
            - syslog_drain
            - route_forwarding
            - volume_mount
        bindable:
          type: boolean
        metadata:
          $ref: '#/components/schemas/Metadata'
        dashboard_client:
          $ref: '#/components/schemas/DashboardClient'
        binding_rotatable:
          type: boolean
        plan_updateable:
          type: boolean
        plans:
          type: array
          items:
            $ref: '#/components/schemas/Plan'
      example:
        bindable: true
        metadata: {}
        plan_updateable: true
        plans:
        - metadata: null
          bindable: true
          maintenance_info:
            description: description
            version: version
          schemas:
            service_binding:
              create: null
            service_instance:
              create:
                parameters: {}
              update: null
          name: name
          description: description
          id: id
          free: true
        - metadata: null
          bindable: true
          maintenance_info:
            description: description
            version: version
          schemas:
            service_binding:
              create: null
            service_instance:
              create:
                parameters: {}
              update: null
          name: name
          description: description
          id: id
          free: true
        name: name
        binding_rotatable: true
        description: description
        id: id
        dashboard_client:
          id: id
          secret: secret
          redirect_uri: redirect_uri
        tags:
        - tags
        - tags
        requires:
        - syslog_drain
        - syslog_drain
    DashboardClient:
      type: object
      properties:
        id:
          type: string
        secret:
          type: string
        redirect_uri:
          type: string
      example:
        id: id
        secret: secret
        redirect_uri: redirect_uri
    Plan:
      required:
      - description
      - id
      - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        metadata:
          $ref: '#/components/schemas/Metadata'
        maintenance_info:
          $ref: '#/components/schemas/MaintenanceInfo'
        free:
          type: boolean
          default: true
        bindable:
          type: boolean
        schemas:
          $ref: '#/components/schemas/Schemas'
      example:
        metadata: null
        bindable: true
        maintenance_info:
          description: description
          version: version
        schemas:
          service_binding:
            create: null
          service_instance:
            create:
              parameters: {}
            update: null
        name: name
        description: description
        id: id
        free: true
    Schemas:
      type: object
      properties:
        service_instance:
          $ref: '#/components/schemas/ServiceInstanceSchema'
        service_binding:
          $ref: '#/components/schemas/ServiceBindingSchema'
      example:
        service_binding:
          create: null
        service_instance:
          create:
            parameters: {}
          update: null
    ServiceInstanceSchema:
      type: object
      properties:
        create:
          $ref: '#/components/schemas/ServiceInstanceSchema_create'
        update:
          $ref: '#/components/schemas/ServiceInstanceSchema_create'
      example:
        create:
          parameters: {}
        update: null
    ServiceBindingSchema:
      type: object
      properties:
        create:
          $ref: '#/components/schemas/ServiceInstanceSchema_create'
      example:
        create: null
    ServiceInstanceResource:
      type: object
      properties:
        service_id:
          type: string
        plan_id:
          type: string
        dashboard_url:
          type: string
        parameters:
          $ref: '#/components/schemas/Object'
        maintenance_info:
          $ref: '#/components/schemas/MaintenanceInfo'
        metadata:
          $ref: '#/components/schemas/ServiceInstanceMetadata'
      example:
        metadata:
          attributes: {}
          labels: {}
        maintenance_info:
          description: description
          version: version
        service_id: service_id
        dashboard_url: dashboard_url
        parameters: {}
        plan_id: plan_id
    ServiceInstanceProvisionRequestBody:
      required:
      - organization_guid
      - plan_id
      - service_id
      - space_guid
      type: object
      properties:
        service_id:
          type: string
        plan_id:
          type: string
        context:
          $ref: '#/components/schemas/Context'
        organization_guid:
          type: string
          deprecated: true
        space_guid:
          type: string
          deprecated: true
        parameters:
          $ref: '#/components/schemas/Object'
    ServiceInstanceProvisionResponse:
      type: object
      properties:
        dashboard_url:
          type: string
        metadata:
          $ref: '#/components/schemas/ServiceInstanceMetadata'
      example:
        metadata:
          attributes: {}
          labels: {}
        dashboard_url: dashboard_url
    ServiceInstanceAsyncOperation:
      type: object
      properties:
        dashboard_url:
          type: string
        operation:
          type: string
        metadata:
          $ref: '#/components/schemas/ServiceInstanceMetadata'
    ServiceInstanceMetadata:
      type: object
      properties:
        labels:
          type: object
        attributes:
          type: object
      example:
        attributes: {}
        labels: {}
    ServiceInstanceUpdateRequestBody:
      required:
      - service_id
      type: object
      properties:
        context:
          $ref: '#/components/schemas/Context'
        service_id:
          type: string
        plan_id:
          type: string
        parameters:
          $ref: '#/components/schemas/Object'
        previous_values:
          $ref: '#/components/schemas/ServiceInstancePreviousValues'
    ServiceInstancePreviousValues:
      type: object
      properties:
        service_id:
          type: string
          deprecated: true
        plan_id:
          type: string
        organization_id:
          type: string
          deprecated: true
        space_id:
          type: string
          deprecated: true
    AsyncOperation:
      type: object
      properties:
        operation:
          type: string
    LastOperationResource:
      required:
      - state
      type: object
      properties:
        state:
          type: string
          enum:
          - in progress
          - succeeded
          - failed
        description:
          type: string
        instance_usable:
          type: boolean
        update_repeatable:
          type: boolean
      example:
        instance_usable: true
        update_repeatable: true
        description: description
        state: in progress
    ServiceBindingResource:
      type: object
      properties:
        metadata:
          $ref: '#/components/schemas/ServiceBindingMetadata'
        credentials:
          $ref: '#/components/schemas/Object'
        syslog_drain_url:
          type: string
        route_service_url:
          type: string
        volume_mounts:
          type: array
          items:
            $ref: '#/components/schemas/ServiceBindingVolumeMount'
        endpoints:
          type: array
          items:
            $ref: '#/components/schemas/ServiceBindingEndpoint'
        parameters:
          $ref: '#/components/schemas/Object'
      example:
        metadata:
          expires_at: expires_at
          renew_before: renew_before
        route_service_url: route_service_url
        endpoints:
        - protocol: tcp
          host: host
          ports:
          - ports
          - ports
        - protocol: tcp
          host: host
          ports:
          - ports
          - ports
        credentials: {}
        syslog_drain_url: syslog_drain_url
        volume_mounts:
        - mode: r
          driver: driver
          device_type: shared
          device:
            volume_id: volume_id
            mount_config: null
          container_dir: container_dir
        - mode: r
          driver: driver
          device_type: shared
          device:
            volume_id: volume_id
            mount_config: null
          container_dir: container_dir
        parameters: null
    ServiceBindingRequest:
      required:
      - plan_id
      - service_id
      type: object
      properties:
        context:
          $ref: '#/components/schemas/Context'
        service_id:
          type: string
        plan_id:
          type: string
        app_guid:
          type: string
          deprecated: true
        bind_resource:
          $ref: '#/components/schemas/ServiceBindingResouceObject'
        parameters:
          $ref: '#/components/schemas/Object'
        predecessor_binding_id:
          type: string
    ServiceBindingMetadata:
      type: object
      properties:
        expires_at:
          type: string
        renew_before:
          type: string
      example:
        expires_at: expires_at
        renew_before: renew_before
    ServiceBindingResouceObject:
      type: object
      properties:
        app_guid:
          type: string
        route:
          type: string
    ServiceBindingResponse:
      type: object
      properties:
        metadata:
          $ref: '#/components/schemas/ServiceBindingMetadata'
        credentials:
          $ref: '#/components/schemas/Object'
        syslog_drain_url:
          type: string
        route_service_url:
          type: string
        volume_mounts:
          type: array
          items:
            $ref: '#/components/schemas/ServiceBindingVolumeMount'
        endpoints:
          type: array
          items:
            $ref: '#/components/schemas/ServiceBindingEndpoint'
      example:
        metadata:
          expires_at: expires_at
          renew_before: renew_before
        route_service_url: route_service_url
        endpoints:
        - protocol: tcp
          host: host
          ports:
          - ports
          - ports
        - protocol: tcp
          host: host
          ports:
          - ports
          - ports
        credentials: {}
        syslog_drain_url: syslog_drain_url
        volume_mounts:
        - mode: r
          driver: driver
          device_type: shared
          device:
            volume_id: volume_id
            mount_config: null
          container_dir: container_dir
        - mode: r
          driver: driver
          device_type: shared
          device:
            volume_id: volume_id
            mount_config: null
          container_dir: container_dir
    ServiceBindingEndpoint:
      required:
      - host
      - ports
      type: object
      properties:
        host:
          type: string
        ports:
          type: array
          items:
            type: string
        protocol:
          type: string
          default: tcp
          enum:
          - tcp
          - udp
          - all
      example:
        protocol: tcp
        host: host
        ports:
        - ports
        - ports
    ServiceBindingVolumeMount:
      required:
      - container_dir
      - device
      - device_type
      - driver
      - mode
      type: object
      properties:
        driver:
          type: string
        container_dir:
          type: string
        mode:
          type: string
          enum:
          - r
          - rw
        device_type:
          type: string
          enum:
          - shared
        device:
          $ref: '#/components/schemas/ServiceBindingVolumeMountDevice'
      example:
        mode: r
        driver: driver
        device_type: shared
        device:
          volume_id: volume_id
          mount_config: null
        container_dir: container_dir
    ServiceBindingVolumeMountDevice:
      required:
      - volume_id
      type: object
      properties:
        volume_id:
          type: string
        mount_config:
          $ref: '#/components/schemas/Object'
      example:
        volume_id: volume_id
        mount_config: null
    Context:
      type: object
      description: "See [Context Conventions](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#context-object)\
        \ for more details."
    Metadata:
      type: object
      description: "See [Service Metadata Conventions](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#service-metadata)\
        \ for more details."
    MaintenanceInfo:
      required:
      - version
      type: object
      properties:
        version:
          type: string
        description:
          type: string
      example:
        description: description
        version: version
    Object:
      type: object
    Error:
      type: object
      properties:
        error:
          type: string
        description:
          type: string
        instance_usable:
          type: boolean
        update_repeatable:
          type: boolean
      description: "See [Service Broker Errors](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#service-broker-errors)\
        \ for more details."
    ServiceInstanceSchema_create:
      type: object
      properties:
        parameters:
          type: object
      example:
        parameters: {}
  parameters:
    APIVersion:
      name: X-Broker-API-Version
      in: header
      description: version number of the Service Broker API that the Platform will
        use
      required: true
      style: simple
      explode: false
      schema:
        type: string
        default: "2.13"
    OriginatingIdentity:
      name: X-Broker-API-Originating-Identity
      in: header
      description: identity of the user that initiated the request from the Platform
      required: false
      style: simple
      explode: false
      schema:
        type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
